name: Build Website to EXE

on:
  workflow_dispatch:
    inputs:
      zip_url:
        description: 'URL du fichier ZIP'
        required: true

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write # TRÈS IMPORTANT pour permettre la création de la Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Download Zip from Website
        run: Invoke-WebRequest -Uri "${{ github.event.inputs.zip_url }}" -OutFile "site.zip"

      - name: Extract Website Files
        run: |
          if (Test-Path src) { Remove-Item -Recurse -Force src }
          Expand-Archive site.zip -DestinationPath src/

      - name: Install and Build EXE
        run: |
          npm install
          npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Suppression des anciennes releases pour ne pas encombrer le dépôt
      - name: Delete old Releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Création de la nouvelle Release avec le fichier EXE
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "latest-build"
          name: "Votre application est prête"
          draft: false
          prerelease: false
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
